### Import numpy

In [1]:
import numpy as np

In [3]:
np.__version__

'2.2.1'

### Array creation
There are 6 general mechanisms for creating arrays:
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

#### 1) Converting Python sequences to NumPy arrays
* NumPy arrays can be defined using Python sequences such as lists and tuples.
* Lists and tuples can define ndarray creation:
* list of numbers will create a 1D array.
* list of lists will create a 2D array.
* further nested lists will create higher-dimensional arrays.

In [5]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("One Dimensional array\n",a1D)
print("Two Dimensional array\n",a2D)
print("Three Dimensional array\n",a3D)

One Dimensional array
 [1 2 3 4]
Two Dimensional array
 [[1 2]
 [3 4]]
Three Dimensional array
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


####  dtype
* When you use numpy.array to define a new array, you should consider the dtype of the elements in the array, which can be specified explicitly.
* This feature gives you more control over the underlying data structures

In [9]:
import numpy as np
d = np.array([127, 128, 129], dtype=np.int16)
print(d)
print(type(d))

[127 128 129]
<class 'numpy.ndarray'>


### Creating of array with the help of tuple

In [12]:
arr_from_tuple = np.array((5, 6, 7), dtype=np.int16)
print("From tuple:", arr_from_tuple)

From tuple: [5 6 7]


### 2) Intrinsic NumPy array creation functions
* NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines.
* These functions can be split into roughly three categories, based on the dimension of the array they create:
    * 1D arrays
    * 2D arrays
    * ndarrays

### A. 1D Array
#### 1. numpy.arange
* This function creates an array with regularly spaced values, similar to Python’s built-in range() function, but it returns a NumPy array
* Syntax : np.arange([start, ]stop, [step, ], dtype=None)


In [14]:
arr1 = np.arange(10)
print(arr1)  
arr2 = np.arange(1, 10, 2)
print(arr2) 
arr3 = np.arange(0, 1, 0.2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8]


#### 2. numpy.linspace 
* This function creates an array with evenly spaced values over a specified range.
* Unlike np.arange(), you specify the number of samples you want, and NumPy will calculate the spacing for you.
* Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    - The function numpy.linspace(start, stop, num=50, endpoint=True, ...):

    * start: The starting value of the sequence.
    * stop: The ending value of the sequence.
    * num: Number of samples to generate.
    * endpoint=True: If True (default), stop is included.


In [56]:
arr1 = np.linspace(0, 10, 5)
print(arr1)  
arr2 = np.linspace(1, 3, 4)
print(arr2)  
arr3 = np.linspace(-1, 1, 6)
print(arr3) 


[ 0.   2.5  5.   7.5 10. ]
[1.         1.66666667 2.33333333 3.        ]
[-1.  -0.6 -0.2  0.2  0.6  1. ]


### 3. numpy.logspace
* The numpy.logspace() function is used to create an array of numbers that are spaced evenly on a logarithmic scale.
* This is particularly useful when you need to generate numbers for scientific or engineering applications where data spans multiple orders of magnitude (like in logarithmic plots, frequency analysis, or when working with powers of 10).
* syntax  : numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)


In [63]:
# Generate 5 numbers between 10^1 (10) and 10^3 (1000) spaced evenly on a logarithmic scale:
arr = np.logspace(1, 3, num=5)
print(arr)
# Generate 6 numbers between 2^1(2) and 2^5(32) with a base of 2
arr = np.logspace(1, 5, num=6, base=2)
print(arr)
# Generate 4 numbers between 10^0(1) and 10^2 (100), excluding the endpoint:
arr = np.logspace(0, 2, num=4, endpoint=False)
print(arr)


[  10.           31.6227766   100.          316.22776602 1000.        ]
[ 2.          3.48220225  6.06286627 10.55606329 18.37917368 32.        ]
[ 1.          3.16227766 10.         31.6227766 ]


In [75]:
3.48220225/2

1.741101125

### 2 - 2D array creation functions
#### 1. np.ones()
* Creates an array filled with 1s.
* Syntax: np.ones(shape, dtype=None)

    *  shape --	Tuple representing array dimensions
    *  dtype --	Data type (default = float64)

In [28]:
np.ones(3)  

array([1., 1., 1.])

In [30]:
np.ones((2, 3))   

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 2. np.zeros():
* Creates an array filled with 0s.The default dtype is float64:
* np.zeros(shape, dtype=None)
    * shape -- Tuple of dimensions
    * dtype	-- Data type (default = float64)

In [35]:
np.zeros(4)  

array([0., 0., 0., 0.])

In [37]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((3, 1), int)

array([[0],
       [0],
       [0]])

#### 3. np.eye()
* Creates a 2D identity matrix, with 1s on the diagonal and 0s elsewhere.The elements where i=j (row index and column index are equal) are 1 and the rest are 0
* Syntax : np.eye(N, M=None, k=0, dtype=float)
     * N -- 	Number of rows
    * M --	Number of columns (default = N)
    * k --	Index of diagonal (0 = main, +1 = above, -1 = below)

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [53]:
np.eye(3, k=-1)  

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [55]:
np.eye(5, k=-1)  

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [57]:
np.eye(5, k=1)  

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.eye(5, k=0)  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 4.numpy.diag
* Extract a diagonal or construct a diagonal array.
    * Extracts a diagonal from a matrix,
    * Creates a diagonal matrix from a 1D array.
* Syntax :- np.diag(v, k=0)
    * v -- 1D or 2D array-like
          ->  If v is a 2-D array, return a copy of its k-th diagonal(Extract).If v is a 1-D array, return a 2-D array with v on the k-th diagonal(Creates).
    * k	-- Diagonal offset (default = 0)
    * k=0: main diagonal, k>0: above, k<0: below
      

##### 1: Create diagonal matrix from vector

In [72]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [74]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [79]:
np.diag([1, 2, 3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

##### 2: Extract diagonal matrix from vector

In [83]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.diag(x)

array([0, 4, 8])

#### 5 vander(x, n) 
* Defines a Vandermonde matrix as a 2D NumPy array. 
* Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1. 
* This array creation routine is helpful in generating linear least squares models, polynomial fitting and linear algebra.
* Syntax - np.vander(x, N=None, increasing=False)
* | Parameter    | Description                                                  |
| ------------ | ------------------------------------------------------------ |
| `x`          | 1D input array                                               |
| `N`          | Number of columns in output (default = len(x))               |
| `increasing` | Order of powers (default = `False`, i.e., decreasing powers) |


#### Vander Monde Matrix
A Vandermonde matrix is a special type of matrix where each row is a geometric progression of the input vector elements.

Formally, given a 1D array:

* x = [x₁, x₂, x₃, ..., xₙ]
* V[i, j] = x[i] ** (N - j - 1)    (default decreasing powers)
Example:-
* Input: [1, 2, 3]
* Each row is: [x**2, x**1, x**0] → [x², x, 1]
       
        Row 1: 1², 1, 1
        
        Row 2: 2², 2, 1
        
        Row 3: 3², 3, 1

#####  1: Default Vandermonde matrix (decreasing powers)

In [95]:
np.vander([1, 2, 3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

##### 2: Increasing power order

In [98]:
np.vander([1, 2, 3], increasing=True)

array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

##### 3: Specify number of columns

In [101]:
np.vander([1, 2, 3], N=4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]])

In [269]:
print(np.full((2, 2), 7))

[[7 7]
 [7 7]]


### 3) Replicating, joining, or mutating existing arrays

Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

#### 1. np.tile() 
* Replicates an array along specified axes to form a larger array — like repeating a pattern.
* Syntax --  np.tile(A, reps)
* | Parameter | Description                                          |
| --------- | ---------------------------------------------------- |
| `A`       | Input array                                          |
| `reps`    | Number of repetitions along each axis (int or tuple) |



#### 1: Repeat 1D array

In [116]:
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

#### 2: Repeat a 2D array along rows and columns



In [119]:
a = np.array([[1, 2], [3, 4]])
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

#### 3: Single-axis repetition

In [126]:
np.tile([[1, 2]], (3, 1))

array([[1, 2],
       [1, 2],
       [1, 2]])

#### 2. np.concatenate()
* Joins two or more arrays along an existing axis (row-wise or column-wise).
* Syntax - np.concatenate((a1, a2, ...), axis=0)
* | Parameter    | Description                                    |
| ------------ | ---------------------------------------------- |
| `a1, a2,...` | Tuple of arrays                                |
| `axis`       | Axis to concatenate on (0 = rows, 1 = columns) |


##### 1: Concatenate 1D arrays

In [131]:
np.concatenate(([1, 2], [3, 4]))

array([1, 2, 3, 4])

In [135]:
np.concatenate((['1', '2'], ['3', '4']))

array(['1', '2', '3', '4'], dtype='<U1')

In [143]:
np.concatenate((['1', '2'], [3, 4]))

array(['1', '2', '3', '4'], dtype='<U21')

##### 2: Concatenate 2D arrays row-wise

In [149]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4]])

##### 3: Concatenate 2D arrays column-wise

In [166]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])
np.concatenate((a, b), axis=1)

array([[1, 3],
       [2, 4]])

In [168]:
a = np.array([[1, 2],[7,8]])
b = np.array([[3, 4]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [7, 8],
       [3, 4]])

#### 3.np.reshape()
* Gives a new shape to an array without changing its data.
* np.reshape(a, newshape)
* | Parameter  | Description               |
| ---------- | ------------------------- |
| `a`        | Input array               |
| `newshape` | New shape as int or tuple |


##### 1: Reshape 1D to 2D

In [171]:
a = np.arange(6)
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

##### 2: Use -1 to auto-calculate dimension

In [177]:
a = np.arange(12)
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### 3: Reshape into 3D

In [180]:
a = np.arange(8)
np.reshape(a, (2, 2, 2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### 4. np.copy()
* np.copy() creates a deep copy of a NumPy array.
* The copied array is completely independent of the original.
* Changes made to the original array do not affect the copy, and vice versa.
* Syntax -- np.copy(a)
* | Parameter | Description              |
| --------- | ------------------------ |
| `a`       | Input array to be copied |


In [186]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

b = a 
b

In [190]:
b[0] = 99
b

array([99,  2,  3])

In [192]:
a

array([99,  2,  3])

#### To prevent this, use np.copy().

#### 1: Copying an array

In [195]:
a = np.array([1, 2, 3])
b = np.copy(a)
b[0] = 99

print("Original a:", a)  # [1 2 3]
print("Copied b:", b)    # [99 2 3]


Original a: [1 2 3]
Copied b: [99  2  3]


##### 2: Copying a 2D array

m1 = np.array([[1, 2], [3, 4]])
m2 = np.copy(m1)
m2[0, 0] = 100

print("Original:\n", m1)
print("Copied:\n", m2)


##### 3: Without copy (default assignment)

In [202]:
x = np.array([10, 20, 30])
y = x          # Just a reference
y[1] = 200

print("x:", x)  # [10 200 30] ❗ changed
print("y:", y)

x: [ 10 200  30]
y: [ 10 200  30]


### Array Properties

.ndim, .shape, .size, and .dtype
 * These attributes help you inspect the structure and type of a NumPy array — essential for writing efficient, bug-free data science or ML code.

#### 1. .ndim → Number of Dimensions
Returns the number of dimensions (a.k.a. axes) of the array.

In [213]:
a = np.array([1, 2, 3])
print(a.ndim)

1


In [215]:
b = np.array([[1, 2], [3, 4]])
print(b.ndim) 

2


In [217]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c.ndim) 

3


#### 2. .shape → Dimensions of the Array
Returns a tuple representing the size of each dimension (rows, columns, etc.).

In [221]:
a = np.array([1, 2, 3])
print(a.shape) 

(3,)


In [233]:
arr1 = np.linspace(0, 10, 5)
arr1.shape  # Output: (3,) → 3 elements in 1D


(5,)

In [231]:
b = np.array([[1, 2], [3, 4]])
print(b.shape)  # Output: (2, 2) → 2 rows × 2 columns

(2, 2)


In [235]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c.shape)   # Output: (2, 2, 1) → 3D array

(2, 2, 1)


### 3.size → Total Number of Elements
Returns the total number of elements in the array.

In [238]:
a = np.array([1, 2, 3, 4])
print(a.size) 

4


In [240]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b.size)  # Output: 6 (3 rows × 2 cols)

6


In [242]:
c = np.zeros((3, 4, 2))
print(c)
print(c.size)   # Output: 24 (3×4×2)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
24


#### 4. dtype → Data Type of Elements
Returns the data type of the elements stored in the array.

In [245]:
a = np.array([1, 2, 3])
print(a.dtype)  

int64


In [249]:
b = np.array([1.0, 2.0])
print(b.dtype)

float64


In [251]:
c = np.array([True, False])
print(c.dtype) 

bool


In [253]:
d = np.array([1, 2], dtype=np.float32)
print(d.dtype)

float32


In [255]:
e = np.array([True, 1])
print(e.dtype) 

int64


bool → int → float → complex → object (promotion hierarchy)

In [258]:
import numpy as np

e1 = np.array([True, 1])       # → int
e2 = np.array([1, 1.0,True])     # → float
e3 = np.array([True, 'yes'])   # → string
e4 = np.array([True, None])    # → object

print(e1, e1.dtype)
print(e2, e2.dtype)
print(e3, e3.dtype)
print(e4, e4.dtype)

[1 1] int64
[1. 1. 1.] float64
['True' 'yes'] <U5
[True None] object


In [264]:
b = np.array(['apple', 42, [1, 2]], dtype=object)
print(b.dtype)

object


In [266]:
b

array(['apple', 42, list([1, 2])], dtype=object)

#### object datatype
* Each element is a full Python object.
* No restriction on length or type.
* More like a general-purpose Python list.

### Reshapinf Array

#### 1. reshape()
Reshape an array to a new shape without changing its data.

#### 2. ravel()
* Flattens a multi-dimensional array to 1D, returns a view (no data copy if possible).
* Syntax -- arr.ravel()

##### 1: Flatten 2D

In [282]:
a = np.array([[1, 2], [3, 4]])
a.ravel()

array([1, 2, 3, 4])

#### 2: Flatten 3D

In [296]:
a = np.arange(8).reshape(2, 2, 2)
a.ravel() 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [298]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### 3: Modify original affects view

In [288]:
b = a.ravel()
b[0] = 999
print(a[0, 0, 0])  # Also becomes 999


999


### 3. flatten()
Returns a 1D copy of the array (unlike ravel(), which returns a view).
Syntax - arr.flatten(order='C')
* order='C' (row-major), 'F' (column-major)

#### 1: Flatten 2D

In [301]:
a = np.array([[1, 2], [3, 4]])
a.flatten()

array([1, 2, 3, 4])

a

#### 2: Change does NOT affect original

In [306]:
b = a.flatten()
b[0] = 100
print(a[0, 0])

1


### 3: Flatten with column-major order

In [315]:
a.flatten(order='F')

array([1, 3, 2, 4])

In [311]:
a = np.array([[1, 2], [3, 4]])
a.flatten(order='C')

array([1, 2, 3, 4])

In [313]:
a

array([[1, 2],
       [3, 4]])

### 4. transpose()
* Swaps the axes of the array.
* Syntax: arr.transpose(*axes)  # or arr.T
* .T is shorthand for 2D arrays (swaps rows and columns)

#### 1: Transpose 2D

In [322]:
a = np.array([[1, 2], [3, 4]])
a.T

array([[1, 3],
       [2, 4]])

#### 2: Transpose 3D

In [327]:
a = np.arange(24).reshape(2, 3, 4)
print(a)
a.transpose(1, 0, 2).shape  # (3, 2, 4)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(3, 2, 4)

In [329]:
a.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

* original shape: (axis0, axis1, axis2) = (2, 3, 4)
* new shape:      (axis1, axis0, axis2) = (3, 2, 4)
| Old Axis    | New Position |
| ----------- | ------------ |
| 0 (blocks)  | 1st axis     |
| 1 (rows)    | 0th axis     |
| 2 (columns) | stays as 2nd |


| Function      | Purpose        | Copy or View?      | Notes                             |
| ------------- | -------------- | ------------------ | --------------------------------- |
| `reshape()`   | Change shape   | View (if possible) | Use `-1` to auto-compute size     |
| `ravel()`     | Flatten to 1D  | View               | Faster, memory efficient          |
| `flatten()`   | Flatten to 1D  | Copy               | Safe; original remains unchanged  |
| `transpose()` | Rearrange axes | View               | `.T` is shortcut for 2D transpose |


### Indexing & Slicing

#### What is Indexing?
Indexing means accessing individual elements or groups of elements from an array using their position (index). NumPy uses zero-based indexing — the first element is at index 0.

### Types of Indexing
#### 1. Basic Indexing
Works like Python lists: use integer indices to access elements.

In [337]:
a = np.array([10, 20, 30, 40])

print(a[0])   # 10
print(a[-1]) 

10
40


In [339]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b[0, 1])  # 2 (row 0, column 1)
print(b[1][2])  # 6 (row 1, column 2)


2
6


#### 2. Slicing
* Returns a view (not a copy) of the array — allows extracting subarrays.
* syntax -- arr[start:stop:step]

In [344]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])     # [20 30 40]
print(a[:3])      # [10 20 30]
print(a[::2]) 

[20 30 40]
[10 20 30]
[10 30 50]


In [348]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0:2, 1:3] )  # [[2 3], [5 6]]
print(b[:, 1]  )     # [2 5 8] (all rows, column 1)
print(b[::2, ::2] )  # [[1 3], [7 9]]


[[2 3]
 [5 6]]
[2 5 8]
[[1 3]
 [7 9]]


### Advanced Indexing
#### 3. Integer Array Indexing
Use arrays of integers to access multiple specific elements.

In [352]:
a = np.array([10, 20, 30, 40])
indices = [0, 2]
a[indices]

array([10, 30])

#### 4. Boolean Indexing
Use a boolean array to select elements where the condition is True.

In [357]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
a[mask]       # [4, 5]



array([4, 5])

In [359]:
# or directly
a[a % 2 == 0] # [2, 4]

array([2, 4])

In [361]:
# 1: Modify using slice
a = np.array([10, 20, 30, 40])
b = a[1:3]
b[0] = 999
print(a)

[ 10 999  30  40]


In [363]:
 # 2: Fancy indexing (non-contiguous)
a = np.array([10, 20, 30, 40, 50])
idx = [0, 3, 4]
a[idx]  # [10, 40, 50]


array([10, 40, 50])

In [365]:
### 3: Boolean filter
a = np.arange(10)
a[a % 3 == 0]  # [0, 3, 6, 9]


array([0, 3, 6, 9])

### Mathematical Operations

### Element-wise Operations
#### What Does "Element-wise" Mean?
It means the operation is applied individually to each pair of elements from two arrays of the same shape — just like how you add two numbers, but done vectorized (efficiently, in bulk).

⚠️ Arrays must be broadcast-compatible (i.e. same shape or follow broadcasting rules).

### Common Element-wise Operations

| Operation      | Symbol / Function      |
| -------------- | ---------------------- |
| Addition       | `+` or `np.add()`      |
| Subtraction    | `-` or `np.subtract()` |
| Multiplication | `*` or `np.multiply()` |
| Division       | `/` or `np.divide()`   |
| Power          | `**` or `np.power()`   |
| Modulo         | `%` or `np.mod()`      |


In [377]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

In [406]:
c = np.array([[1, 2],
              [3, 4]])

d = np.array([[5, 6],
              [7, 8]])

#### 1. Addition

In [374]:
np.add(a, b)

array([5, 7, 9])

In [379]:
a + b 

array([5, 7, 9])

In [408]:
c + d

array([[ 6,  8],
       [10, 12]])

#### 2. Subtraction

In [383]:
np.subtract(a, b)

array([-3, -3, -3])

In [385]:
a - b  

array([-3, -3, -3])

In [410]:
c - d

array([[-4, -4],
       [-4, -4]])

In [412]:
d - c

array([[4, 4],
       [4, 4]])

#### 3. Multiplication

In [388]:
a * b       

array([ 4, 10, 18])

In [390]:
np.multiply(a, b)

array([ 4, 10, 18])

In [414]:
c * d

array([[ 5, 12],
       [21, 32]])

#### 4. Division

In [393]:
a / b  

array([0.25, 0.4 , 0.5 ])

In [395]:
np.divide(a, b)

array([0.25, 0.4 , 0.5 ])

In [416]:
d / c

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

#### 5. Power

In [400]:
a ** 2  

array([1, 4, 9])

In [402]:
np.power(a, 2)

array([1, 4, 9])

In [404]:
b % a        # Output: [0 1 0]
np.mod(b, a)

array([0, 1, 0])

In [418]:
c ** 2

array([[ 1,  4],
       [ 9, 16]])

### 2. Broadcasting with Scalars/Scalar Operations

Operations can be done between an array and a single number (scalar), and NumPy automatically applies it to each element:

In [422]:
a = np.array([1, 2, 3])

a + 5  

array([6, 7, 8])

In [424]:
a

array([1, 2, 3])

In [426]:
a * 10  

array([10, 20, 30])

In [428]:
a ** 2 

array([1, 4, 9])

In [430]:
a

array([1, 2, 3])

In [432]:
b

array([4, 5, 6])

In [440]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Aggregation Functions
#### What are Aggregation Functions?
* Aggregation functions reduce an array to a single value (like a sum, mean, etc.), or collapse dimensions using statistical operations.
* They help you summarize data:
    * How many? (count)
    * How big? (max, min)
    * What’s the average? (mean)
    * How spread out? (std, var)
####  Common Aggregation Functions
| Function    | Description             |
| ----------- | ----------------------- |
| `sum()`     | Total of all elements   |
| `min()`     | Smallest element        |
| `max()`     | Largest element         |
| `mean()`    | Average of all elements |
| `std()`     | Standard deviation      |
| `var()`     | Variance                |
| `prod()`    | Product of all elements |
| `cumsum()`  | Cumulative sum          |
| `cumprod()` | Cumulative product      |
| `argmin()`  | Index of minimum value  |
| `argmax()`  | Index of maximum value  |


In [475]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

#### Basic Aggregations

In [477]:
print("Sum:", np.sum(a))             # 21
print("Minimum:", np.min(a))         # 1
print("Maximum:", np.max(a))         # 6
print("Mean:", np.mean(a))           # 3.5
print("Standard Deviation:", np.std(a))   # ~1.707
print("Variance:", np.var(a))             # ~2.916
print("Product of all elements:", np.prod(a))
print("Mean of all elements:",np.mean(a))

Sum: 21
Minimum: 1
Maximum: 6
Mean: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Product of all elements: 720
Mean of all elements: 3.5


#### Aggregation by Axis

In [452]:
np.sum(a, axis=0) # → column-wise sum

array([5, 7, 9])

In [454]:
np.sum(a, axis=1) #→ row-wise sum

array([ 6, 15])

#### Cumulative Functions

In [457]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [459]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

In [461]:
np.cumprod(a)

array([  1,   2,   6,  24, 120, 720])

#### Index of Min/Max

In [471]:
print(np.argmax(a))  # 5 → position of largest value (6)
print(np.argmin(a))   # 0 → position of smallest value (1)


0
1


### Sorting and Searching in NumPy
#### 1. Sorting
* NumPy provides multiple ways to sort arrays, either in-place or by returning a sorted copy.

  
#### 1. np.sort()
* Returns a sorted copy of the array
* Can specify axis and order
* Sytax -- np.sort(array, axis=-1, kind='quicksort')
    * axis: default is -1 (last axis)
    * kind: 'quicksort', 'mergesort', 'heapsort', 'stable'

In [481]:
a = np.array([[3, 1, 2],
              [6, 4, 5]])

print("Original:\n", a)

print("\nSorted along rows (axis=1):\n", np.sort(a, axis=1))

print("\nSorted along columns (axis=0):\n", np.sort(a, axis=0))

Original:
 [[3 1 2]
 [6 4 5]]

Sorted along rows (axis=1):
 [[1 2 3]
 [4 5 6]]

Sorted along columns (axis=0):
 [[3 1 2]
 [6 4 5]]


In [483]:
a

array([[3, 1, 2],
       [6, 4, 5]])

#### 2.np.argsort()
Returns the indices that would sort an array.

In [487]:
x = np.array([3, 1, 2])
print(np.argsort(x)) 

[1 2 0]


#### 3. np.lexsort()
Performs indirect sort by multiple keys (like sorting by last name, then first name).

In [498]:
last = np.array(['Smith', 'Aones', 'Williams'])
first = np.array(['John', 'zdam', 'zdam'])

print(np.lexsort((first, last))) # Sorts by last name, then first name

[1 0 2]


### 2. Searching
#### 1. np.where()
Returns indices where a condition is true.

In [501]:
a = np.array([10, 15, 20, 25])
print(np.where(a > 15))  # Output: (array([2, 3]),)


(array([2, 3]),)


In [503]:
np.where(a > 15, 1, 0) #You can also use it for conditional replacement:

array([0, 0, 1, 1])

#### 2. np.searchsorted()
Finds insertion index to maintain order in a sorted array.

In [507]:
a = np.array([1, 3, 5, 7])
print(np.searchsorted(a, 4))  # Output: 2


2


#### 3. np.nonzero()
Returns the indices of non-zero elements.

In [510]:
x = np.array([0, 3, 0, 4])
np.nonzero(x)

(array([1, 3]),)

| Function            | Description                                 |
| ------------------- | ------------------------------------------- |
| `np.sort()`         | Sort values in array                        |
| `np.argsort()`      | Indices that would sort the array           |
| `np.lexsort()`      | Multi-key sorting                           |
| `np.where()`        | Indices (or values) where condition is True |
| `np.searchsorted()` | Find index where element should be inserted |
| `np.nonzero()`      | Indices of non-zero elements                |
